version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: guideforge_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Voor lokale toegang (bijv. via MySQL Workbench)
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    container_name: guideforge_backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies lokaal
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Amsterdam
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    container_name: guideforge_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Voorkom node_modules overschrijven
    ports:
      - "3000:5173"
    environment:
      REACT_APP_API_URL: http://backend:8080/api
      CHOKIDAR_USEPOLLING: true
      HOST: 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: