# Development image based on Maven with Java 21
FROM maven:3.9.6-eclipse-temurin-21
WORKDIR /app

# Copy Maven config and wrapper for caching dependencies
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
RUN mvn dependency:go-offline

# Copy source code (overwritten by bind mount in Docker Compose)
COPY src ./src

# Start Spring Boot in development mode
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.fork=false"]
EXPOSE 8080