name: Backend CI

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping -h db -uroot -p$MYSQL_ROOT_PASSWORD --silent"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=60
          --memory=512m

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be healthy
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          echo "Checking network reachability for host 'db'..."
          sudo apt-get install -y netcat-openbsd
          for i in $(seq 1 30); do
            if nc -z db 3306; then
              echo "TCP connection to db:3306 successful."
              break
            fi
            echo "Port not open yet ($i/30)..."
            sleep 2
          done

          echo "Waiting for MySQL service (db) to accept connections..."
          for i in $(seq 1 60); do
            if mysqladmin ping -h db --protocol=tcp -uroot -p"$MYSQL_ROOT_PASSWORD" --silent; then
              echo "MySQL is ready!"
              exit 0
            fi
            echo "Still waiting ($i/60)..."
            sleep 5
          done
          echo "MySQL failed to start after waiting."
          exit 1

      - name: Debug MySQL connection
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          echo "Listing databases to verify MySQL connection:"
          mysql -h db -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SHOW DATABASES;"

      - name: Run unit tests
        working-directory: ./backend
        run: ./mvnw clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${{ secrets.MYSQL_DATABASE }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Amsterdam
          SPRING_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'backend'
          path: './backend'
          format: 'HTML,JSON'

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dep-check-report
          path: dependency-check-report.html
