name: Backend CI

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping -h db -uroot -p$MYSQL_ROOT_PASSWORD --silent"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=60
          --memory=512m

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Stap 1: Wacht tot MySQL klaar is
      - name: Wait for MySQL
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          echo "Waiting for MySQL to be healthy..."
          for i in $(seq 1 60); do
            if mysqladmin ping -h db -uroot -p"$MYSQL_ROOT_PASSWORD" --silent; then
              echo "MySQL is ready!"
              exit 0
            fi
            echo "Still waiting ($i/60)..."
            sleep 5
          done
          echo "MySQL did not become ready in time."
          exit 1

      # Stap 2: Debug MySQL verbinding (optioneel)
      - name: Debug MySQL connection
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          echo "Listing databases to verify MySQL connection:"
          docker exec $(docker ps -q --filter "name=db") \
            mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SHOW DATABASES;"

      # Stap 3: Run unit tests
      - name: Run unit tests
        working-directory: ./backend
        run: ./mvnw clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${{ secrets.MYSQL_DATABASE }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Amsterdam
          SPRING_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

      # Stap 4: OWASP Dependency Check
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'backend'
          path: './backend'
          format: 'HTML,JSON'

      # Stap 5: Upload Dependency-Check Report
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dep-check-report
          path: dependency-check-report.html