name: Docker Build & Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # handmatig triggeren

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: matthijs/guideforge-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: matthijs/guideforge-frontend:latest
      
      - name: Deploy to Kubernetes
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          kubectl --kubeconfig=kubeconfig apply -f ./k8s/

      - name: Install Helm
        uses: azure/setup-helm@v4
      - run: helm upgrade --install guideforge ./guideforge-chart --values values.yaml --kubeconfig kubeconfig