name: Docker Build & Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/guideforge-backend:latest,${{ secrets.DOCKER_USERNAME }}/guideforge-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/guideforge-frontend:latest,${{ secrets.DOCKER_USERNAME }}/guideforge-frontend:${{ github.sha }}
  
  webhook-request:
    runs-on: ubuntu-latest
    steps:

    - name: Send a request to webhook
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{
          "username": "Notify Deployment",
          "content": "@everyone",
          "embeds": [
            {
              "title": "Deployment to production",
              "description": "**${{ github.actor }}** published to the production`",
              "color": 3447003,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}",
                "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
              }
              ],
              "footer": {
                "text": "Run #${{ github.run_number }} • GitHub Actions",
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "timestamp": "${{ github.event.head_commit.timestamp }}"
            }
          ]
        }' \
        ${{ secrets.WEBHOOK_URL }}
