name: Frontend CI

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies and test
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint -- --fix
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Run frontend tests if available
        working-directory: ./frontend
        run: |
          if npm run | grep -q "test"; then
            echo "Test script found. Running tests..."
            npm test -- --coverage
          else
            echo "No test script defined. Skipping tests."
          fi
        env:
          REACT_APP_API_URL: http://localhost:8080/api

      - name: NPM Audit
        working-directory: ./frontend
        run: npm audit --audit-level=high  # Verlaagd naar high voor debugging