name: Webhook on Event
on: [push, pull_request, issues, issue_comment]

jobs:
  webhook-request:
    runs-on: ubuntu-latest
    steps:
    - name: Send a request to webhook
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{
          "username": "GitHub Actions",
          "content": "@everyone",
          "embeds": [
            {
              "title": "New Event: ${{ github.event_name }}",
              "description": "Triggered by **${{ github.actor }}** on `${{ github.repository }}`",
              "color": 5763719,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}",
                "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
              },
              "fields": [
                {
                  "name": "Repository",
                  "value": "[${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})",
                  "inline": true
                },
                {
                  "name": "Branch",
                  "value": "${{ github.ref_name }}",
                  "inline": true
                },
                {
                  "name": "Commit",
                  "value": "[${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
                }
              ],
              "footer": {
                "text": "Run #${{ github.run_number }} • GitHub Actions",
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "timestamp": "${{ github.event.head_commit.timestamp }}"
            }
          ]
        }' \
        ${{ secrets.WEBHOOK_URL }}
